github.com:
    users:
        wang-edward:
            oauth_token: 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
    git_protocol: https
    user: wang-edward
    oauth_token: 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
